-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointment
(
    id uuid NOT NULL,
    appoint_date timestamp(6) without time zone,
    cabinet_id uuid,
    doctor_id uuid,
    patient_id uuid,
    CONSTRAINT appointment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attachments
(
    id uuid NOT NULL,
    type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT attachments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cabinet
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cabinet_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doctors
(
    id uuid NOT NULL,
    emaildoc character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    patronymic character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    speciality character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tabel_number integer NOT NULL,
    account_id uuid NOT NULL,
    CONSTRAINT doctors_pkey PRIMARY KEY (id),
    CONSTRAINT ukfca1jj0he0x0hdwwidha1c801 UNIQUE (account_id)
);

CREATE TABLE IF NOT EXISTS public.passport
(
    id uuid NOT NULL,
    "number" integer NOT NULL,
    series integer NOT NULL,
    CONSTRAINT passport_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    id uuid NOT NULL,
    bith_date timestamp(6) without time zone,
    citizenship character varying(255) COLLATE pg_catalog."default" NOT NULL,
    emaildoc character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default" NOT NULL,
    height integer,
    lastname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    patronymic character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    snils integer NOT NULL,
    weight integer,
    attach_id uuid,
    passport_id uuid NOT NULL,
    user_account_id uuid NOT NULL,
    CONSTRAINT patients_pkey PRIMARY KEY (id),
    CONSTRAINT ukeynq5ff4k1cjj63o50dqnh2dl UNIQUE (passport_id),
    CONSTRAINT uknsko4dr4j31k0w4jqsuvb27vf UNIQUE (user_account_id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id uuid NOT NULL,
    roles character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    date_created timestamp(6) without time zone,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT fk2mkixgg09ut953ymlrkm9rrfo FOREIGN KEY (cabinet_id)
    REFERENCES public.cabinet (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT fk3mbue9w5cldlnxx3hm15t5sfo FOREIGN KEY (patient_id)
    REFERENCES public.patients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT fk51y2ce12yp0g0hgsa39p2u9jq FOREIGN KEY (doctor_id)
    REFERENCES public.doctors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.doctors
    ADD CONSTRAINT fkkmed29dui9ab52f22r3ap77d4 FOREIGN KEY (account_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukfca1jj0he0x0hdwwidha1c801
    ON public.doctors(account_id);


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT fk2nehgx94qquap3eh8vgga2x32 FOREIGN KEY (attach_id)
    REFERENCES public.attachments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT fkdjdmnwyv5sr3frfy69rvl4gbk FOREIGN KEY (passport_id)
    REFERENCES public.passport (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukeynq5ff4k1cjj63o50dqnh2dl
    ON public.patients(passport_id);


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT fklv40lirre0ht6vhiueo200jqp FOREIGN KEY (user_account_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uknsko4dr4j31k0w4jqsuvb27vf
    ON public.patients(user_account_id);


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;